name: Junit Step Annotate
description: Annotates your build step using JUnit XML reports
author: https://github.com/queimadus
requirements:
  - docker
configuration:
  properties:
    reports-selector:
      type: string
  required:
    - reports-selector
  additionalProperties: false
